---
- name: 'Install and Configure DNSMasq'
  hosts: 'prod_dns_server'

  pre_tasks:
    - name: 'Remove old config files'
      ansible.builtin.file:
        path: '{{ item }}'
        state: 'absent'
      become: true
      with_items:
        - /etc/dnsmasq.d/dhcp.conf
        - /etc/dnsmasq.d/dns.conf

  roles:
    - role: glagasse.dnsmasq
      vars:
        dnsmasq__addn_hosts:
          - {'address': '192.168.1.1',  'name': 'udmpro' }
          - {'address': '192.168.1.2',  'name': 'uswitch16' }
          - {'address': '192.168.1.3',  'name': 'uswitch8' }
          - {'address': '192.168.1.4',  'name': 'codex' }
          - {'address': '192.168.1.5',  'name': 'uapnano' }
          - {'address': '192.168.1.7',  'name': 'pve-01' }
          - {'address': '192.168.1.13',  'name': 'pve04' }
          - {'address': '192.168.1.20',  'name': 'ip-192-168-1-20' }
